In [1]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-08/ipf_lifts.csv')

In [49]:
df.head()

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
0,Hiroyuki Isagawa,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,205.0,140.0,225.0,1,1985-08-03,IPF,World Games
1,David Mannering,M,SBD,Single-ply,24.0,24-34,NaN,67.5,67.5,225.0,132.5,235.0,2,1985-08-03,IPF,World Games
2,Eddy Pengelly,M,SBD,Single-ply,35.5,35-39,NaN,67.5,67.5,245.0,157.5,270.0,3,1985-08-03,IPF,World Games
3,Nanda Talambanua,M,SBD,Single-ply,19.5,20-23,NaN,67.5,67.5,195.0,110.0,240.0,4,1985-08-03,IPF,World Games
4,Göran Henrysson,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,240.0,140.0,215.0,5,1985-08-03,IPF,World Games

In [9]:
df.columns

Index(['name', 'sex', 'event', 'equipment', 'age', 'age_class', 'division',
       'bodyweight_kg', 'weight_class_kg', 'best3squat_kg', 'best3bench_kg',
       'best3deadlift_kg', 'place', 'date', 'federation', 'meet_name'],
      dtype='object')

In [7]:
df.tail()

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
41147,Chien-Hsiung Chao,M,B,Single-ply,NaN,NaN,Open,126.5,125+,NaN,202.5,NaN,12,1995-06-25,IPF,World Bench Press Championships
41148,Oleg Gordynetz,M,B,Single-ply,NaN,NaN,Open,137.5,125+,NaN,202.5,NaN,13,1995-06-25,IPF,World Bench Press Championships
41149,Clive Lambert,M,B,Single-ply,31.5,24-34,Open,142.2,125+,NaN,202.5,NaN,14,1995-06-25,IPF,World Bench Press Championships
41150,Peter Brath,M,B,Single-ply,21.5,20-23,Open,125.5,125+,NaN,180.0,NaN,15,1995-06-25,IPF,World Bench Press Championships
41151,Valery Sidorenko,M,B,Single-ply,38.5,35-39,Open,142.0,125+,NaN,NaN,NaN,DQ,1995-06-25,IPF,World Bench Press Championships

In [ ]:
# df1['Worldwide Gross Dollars'] = df.isna().sum()
# df1[''].isna().sum()
# df1.dropna(axis=0,inplace=True)
#df1[''].fillna(df[''].median(), inplace=True)
# df1[''].fillna(method='ffill', inplace=True)
# df1[''].fillna(method='bfill', inplace=True)
# df1[''].interpolate(method='polynomial')

In [14]:
df.columns

Index(['name', 'sex', 'event', 'equipment', 'age', 'age_class', 'division',
       'bodyweight_kg', 'weight_class_kg', 'best3squat_kg', 'best3bench_kg',
       'best3deadlift_kg', 'place', 'date', 'federation', 'meet_name'],
      dtype='object')

In [16]:
df['age'].isna().sum()

2906

In [35]:
#df.dropna(axis=0,inplace=False)

In [18]:
df.head()

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
0,Hiroyuki Isagawa,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,205.0,140.0,225.0,1,1985-08-03,IPF,World Games
1,David Mannering,M,SBD,Single-ply,24.0,24-34,NaN,67.5,67.5,225.0,132.5,235.0,2,1985-08-03,IPF,World Games
2,Eddy Pengelly,M,SBD,Single-ply,35.5,35-39,NaN,67.5,67.5,245.0,157.5,270.0,3,1985-08-03,IPF,World Games
3,Nanda Talambanua,M,SBD,Single-ply,19.5,20-23,NaN,67.5,67.5,195.0,110.0,240.0,4,1985-08-03,IPF,World Games
4,Göran Henrysson,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,240.0,140.0,215.0,5,1985-08-03,IPF,World Games

In [19]:
df['Nan'] = df.isna().sum()

In [ ]:
#df1[''].fillna(df[''].median(), inplace=True)
# df1[''].fillna(method='bfill', inplace=True)
# df1[''].interpolate(method='polynomial')

In [41]:
df.head()

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
0,Hiroyuki Isagawa,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,205.0,140.0,225.0,1,1985-08-03,IPF,World Games
1,David Mannering,M,SBD,Single-ply,24.0,24-34,NaN,67.5,67.5,225.0,132.5,235.0,2,1985-08-03,IPF,World Games
2,Eddy Pengelly,M,SBD,Single-ply,35.5,35-39,NaN,67.5,67.5,245.0,157.5,270.0,3,1985-08-03,IPF,World Games
3,Nanda Talambanua,M,SBD,Single-ply,19.5,20-23,NaN,67.5,67.5,195.0,110.0,240.0,4,1985-08-03,IPF,World Games
4,Göran Henrysson,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,240.0,140.0,215.0,5,1985-08-03,IPF,World Games

In [27]:
df['age'].fillna(df['age'].median(), inplace=False)

In [39]:
df['age'].fillna(method='ffill', inplace=False)

0         NaN
1        24.0
2        35.5
3        19.5
4        19.5
         ...
41147    28.5
41148    28.5
41149    31.5
41150    21.5
41151    38.5
Name: age, Length: 41152, dtype: float64

In [42]:
df['age'].fillna(method='bfill', inplace=False)

0        24.0
1        24.0
2        35.5
3        19.5
4        32.5
         ...
41147    31.5
41148    31.5
41149    31.5
41150    21.5
41151    38.5
Name: age, Length: 41152, dtype: float64

In [45]:
df['age'].unique()

array([ nan, 24. , 35.5, 19.5, 32.5, 31.5, 40.5, 36.5, 31. , 30.5, 21.5,
       22.5, 25.5, 49.5, 17. , 23.5, 37.5, 41.5, 18.5, 33.5, 44.5, 28.5,
       50.5, 32. , 26.5, 17.5, 29.5, 27.5, 34.5, 42. , 30. , 43.5, 24.5,
       28. , 39.5, 18. , 47. , 46.5, 20.5, 14.5, 29. , 22. , 26. , 42.5,
       16.5, 40. , 27. , 45. , 41. , 33. , 15.5, 35. , 21. , 36. , 38.5,
       23. , 49. , 25. , 34. , 38. , 20. , 48. , 50. , 37. , 48.5, 47.5,
       51. , 39. , 46. , 45.5, 52.5, 54.5, 16. , 19. , 54. , 51.5, 44. ,
       13.5, 53.5, 57.5, 58.5, 52. , 56.5, 61.5, 60.5, 67.5, 65.5, 62.5,
       61. , 63.5, 60. , 59.5, 64.5, 73.5, 71. , 74.5, 69.5, 73. , 70.5,
       75.5, 71.5, 43. , 56. , 53. , 68.5, 87.5, 74. , 15. , 55.5, 58. ,
       66.5, 62. , 68. , 70. , 64. , 81. , 75. , 78.5, 76.5, 55. , 69. ,
       77.5, 72.5, 77. , 65. , 82.5, 63. , 79.5, 72. , 14. , 57. , 66. ,
       78. , 85.5, 76. , 59. , 82. , 83.5, 81.5, 67. , 79. , 80.5, 84.5,
       88.5, 93.5, 80. , 84. , 10.5,  0.5, 86.5, 83. ])

In [46]:
df['age'].value_counts()

22.5    2417
21.5    1994
17.5    1885
20.5    1458
19.5    1071
        ...
93.5       1
79.0       1
82.0       1
81.0       1
83.0       1
Name: age, Length: 150, dtype: int64

In [51]:
df.columns

Index(['name', 'sex', 'event', 'equipment', 'age', 'age_class', 'division',
       'bodyweight_kg', 'weight_class_kg', 'best3squat_kg', 'best3bench_kg',
       'best3deadlift_kg', 'place', 'date', 'federation', 'meet_name'],
      dtype='object')

In [55]:
df['weight_class_kg'].interpolate(method='polynomial')

0        67.5
1        67.5
2        67.5
3        67.5
4        67.5
         ...
41147    125+
41148    125+
41149    125+
41150    125+
41151    125+
Name: weight_class_kg, Length: 41152, dtype: object